/************************************************************************************************
 *                               IMPORTANT LICENSE INFORMATION                                  *
 * This file is part of Ministry Resource Sity by Redmane Digital which is released under RDSL. *
 * See file LICENSE for full license details.                                                   *
 ************************************************************************************************/

import React from 'react';
import Hero from '../components/heroes/Primary';
import heroImg from '../images/about.jpg';
import Layout from '../components/layout';
import SEO from '../components/seo';
import { useTranslations } from 'gatsby-plugin-translate';

const PrivacyPolicy = ({ location }) => {
    const t = useTranslations();
    return (
        <Layout location={location}>
            <SEO title={t`Privacy Policy`} />
            <Hero title={t`Privacy Policy`} imgSources={{ jpg: heroImg }} heading={t`Privacy Policy`} imgStyles={{ position: 'center center' }} imagePosition="center" reducedWidth={true} />
            <div className="container reduced-width my-5">
                <div className="row">
                    <div className="col-md-12">
                        <h2>{t`Privacy Policy`}</h2>
                        <p><em>{t`Updated November 9, 2020`}</em></p>
                        <h2>{t`Definitions`}</h2>
                        <p>{t`We use some short hand throughout this document to make it easier to read. For example, when we say “Mannahouse Resource” or “the Site,” we’re talking about the web-based online site Mannahouse Resource accessible at www.mannahouseresource.com`}</p>
                        <p>{t`Mannahouse Resource is owned and operated by Mannahouse Church, which we’ll refer to as “Mannahouse,” “Mannahouse Church,” “Mannahouse Resource,” “us,” or “we” throughout this policy. We allow use of the Site by registered users, or “Members,” however, unregistered users, or “Users” may browse the Site without creating an account but will have limited access to its content and functionality. Members and Users are collectively referred to in this policy as “you.”`}</p>
                        <h2>{t`Accepting the Terms`}</h2>
                        <p>{t`Please read this Privacy Policy carefully because it discusses how we will collect, use, share and process your personal information, and by accessing Mannahouse Resource you agree to this Privacy Policy and its terms and consent to having your data transferred to and processed in the United States. Your use of Mannahouse Resource is also governed by our Terms of Use. Please read those terms carefully as well.`}</p>
                        <p>{t`We welcome any questions or comments you may have about this Privacy Policy and our privacy practices. If you have any questions or comments, you may contact us at: Attn Global, 9200 NE Fremont St, Portland OR 97220; connect@mannahouseresource.com`}</p>
                        <h2>{t`How We Use Your Information`}</h2>
                        <p>{t`We do not share your personal data with any third-party advertisers or ad networks for their advertising purposes. We use data that we collect about you or that you provide to us, including any personal information, as follows:`}</p>

                        <ol>
                            <li>{t`To provide you with Mannahouse Resource, and any other information, products, or services that you request from us;`}</li>
                            <li>{t`As described in this Privacy Policy;`}</li>
                            <li>{t`To fulfill any other purpose for which you provide it;`}</li>
                            <li>{t`To carry out our obligations and enforce our rights under this Privacy Policy and our Terms of Use;`}</li>
                            <li>{t`In any other way we may describe when you provide the information; and`}</li>
                            <li>{t`For any other purpose with your consent.`}</li>
                        </ol>

                        <p>{t`Your ability to access Mannahouse Resource is not contingent on you providing us with your personal information, and you may decline to submit personal information to us, however, that may prohibit us from providing you with certain Mannahouse Resource content and/or functionality.`}</p>

                        <h2>{t`Facilitating Your Use of Mannahouse Resource`}</h2>
                        <p>{t`We use your personal data to authorize your access to Mannahouse Resource. We also use your personal data to provide certain functionality of the Site depending on the functionality you use and choose and the personal data you agree to provide. We use the data that we have about you to provide, improve, and personalize the Site, including with the help of automated technologies discussed in this policy and the inferences that we make from information we collect.`}</p>
                        <h2>{t`Mannahouse Resource Community`}</h2>
                        <p>{t`Mannahouse Resource will allow Users to communicate and connect with other Users to share ministry experience, ask and answer questions, and grow in relationships via the online community function. It is your choice whether to communicate with others via the Mannahouse Resource Community, and you are responsible for the privacy of the data you share.`}</p>
                        <h2>{t`Communications`}</h2>
                        <p>{t`We may contact you through email or other media to relay Mannahouse Resource updates and news messages. We may also contact you through email or other media to relay information about other products and/or services offered by Mannahouse. You may unsubscribe from these messages via the unsubscribe link in emails providing these messages.`}</p>
                        <h2>{t`Service-Related Messages`}</h2>
                        <p>{t`We may use your information to contact you about account, security, legal and other service-related issues. We will do this through in-app notifications, email, or other channels. Please be aware that you cannot opt-out of receiving service messages (an example is a password reset email) from us, including security and legal notices.`}</p>
                        <h2>{t`Analytics and Performance`}</h2>
                        <p>{t`We use the personal data available to us to observe social, behavioral, economic, and geographic trends as they pertain to ministry. In some cases, we work with trusted third parties to perform this research, under controls that are designed to protect your privacy. We publish or allow others to publish our insights but only in an aggregated form that does not disclose your personally identifiable information. For example we may use your data to generate statistics about overall usage of the Site worldwide and in specific countries and geographic regions.`}</p>
                        <p>{t`We use de-identified and aggregate user data to market the Site, such as celebrating the total number of resources downloaded across the Site. We use data, including user-provided personal information, aggregations of user data, data collected through use of the Site, public feedback and information inferred from this data to conduct internal research and development in order to provide a better overall Site experience, measure the performance of the Site and increase use of the Site and its features. This is done by making changes to the Site that are generally available, as well as sending users messages suggesting Site functionality and content as discussed in this policy.`}</p>
                        <h1>{t`Information We Collect and How We Collect It`}</h1>
                        <h2>{t`Information You Provide to Us`}</h2>
                        <p>{t`You do not have to become a Mannahouse Resource user to view resources and certain pages hosted on the Site. You do need to become a Member to download or otherwise access the resources, training, community, and certain other features of the Site. Membership allows us to ensure you receive the content and functionality you request from the Site as well as to provide technical service and tailor the Site to function to its full potential. To become a Member, you are required to create an account and provide certain information such as your name, email address, ministry name, etc. which will be associated with your Member account.`}</p>
                        <p>{t`Beyond this required information, you have choices about whether to provide additional information to be associated with your Member account. We collect personal data from you when you provide, post, or upload it to the Site. You do not have to provide such information; however, if you do not, it may limit our ability to personalize or fully support the Site and your ability to use the Site to its fullest extent.`}</p>
                        <p>{t`If you choose to link Mannahouse Resource with other websites, applications, and services or profiles you have with third party applications, you will provide the personal data stored on those applications to the Site and Mannahouse. For example, by linking your Facebook account to the Site, you may provide personal information you have opted to share through Facebook to Mannahouse. You may revoke the link with such accounts and third party applications by modifying your settings with those applications.`}</p>
                        <h2>{t`Sensitive Data`}</h2>
                        <p>{t`We do not require that you provide sensitive data such as religious denomination, race, ethnicity, philosophical beliefs, or physical or mental health to create or maintain a Mannahouse Resource account. It is your choice whether to provide such sensitive information should it be an option to do so. If you choose to provide any sensitive information, it may be used by Mannahouse to create a more personalized or efficient Site experience like other non-sensitive information you provide. In any event, Mannahouse will only process sensitive data you provide to us for Mannahouse’s legitimate activities on your behalf and will not disclose this information without your express consent. We will maintain your information subject to appropriate safeguards discussed in this policy and otherwise provided by Mannahouse. Should you have any questions, feel free to contact us at connect@mannahouseresource.com.`}</p>
                        <h2>{t`Use For Other Services`}</h2>
                        <p>{t`We may combine the information you submit under your account with information you provide us through other Mannahouse services and products as well as inferences we make from this information to provide you with a better experience and to improve the quality of all services and products provided to you by Mannahouse.`}</p>
                        <h2>{t`Your Posts and Contributions`}</h2>
                        <p>{t`When the Site allows you to provide information or content to be published, distributed, or displayed, we refer to that as “posted,” which can be on public areas of the Site, websites you access through the Site or transmitted to other users of the Site or third parties, all of which we’ll call “User Contributions.” For example, these include activities such as posting comments about how you conduct ministry, questions about using our services or resources, or personal stories of experiences you have had.`}</p>
                        <p>{t`Please keep in mind that if you disclose personal information in a public manner whether through chat postings, social media, message boards, or other public online forums, this information may be collected and used by others. User Contributions are posted and transmitted at your own risk. We cannot control the actions of other users or third parties with whom you choose to share your User Contributions. Therefore, we cannot and do not guarantee that your User Contributions will not be viewed by unauthorized persons, nor do we accept any liability associated with your User Contributions.`}</p>
                        <h2>{t`Automatic Data Collection Technologies`}</h2>
                        <p><strong>{t`Service Use.`}</strong> {t`We log usage data when you use the Site, including when you view or click on content, browser type, browser language, perform a search or request, the date and time of your request, install an update, seek new functionality, or use one or more tools offered through Mannahouse Resource. We use log-ins, device information internet protocol (“IP”) addresses, and cookies and similar technologies to identify you and log your use.`}</p>
                        <p><strong>{t`Cookies and Other Similar Technologies`}</strong> {t`We use cookies and similar technologies (for example, web beacons, pixels, tags and device identifiers) to recognize you and/or your device(s) on, off, and across the different applications of Mannahouse Resource. Cookies and similar technologies help to facilitate the best possible user experience of the Site as they allow us to recognize you and maintain your user preferences from session to session, help us keep your account safe, and generally improve the functionality of the products and services offered through the Site. They also help us ensure that Member information is used in association with the correct Member account. Importantly, we do not use cookies or similar technologies to facilitate interest-based ads from third parties.`}</p>
                        <p>{t`Although most internet browsers accept cookies and the like by default, you can control these types of technology through your browser settings and similar tools and agree to refuse all cookies altogether. If you refuse to accept cookies and similar technologies by activating the appropriate setting on your browser or smartphone, you may be unable to access certain parts of the Site, prohibiting us from delivering the full capability of the Site and preventing the use of certain features and services that require these technologies.`}</p>
                        <p>{t`By agreeing to our Privacy Policy, you agree to the use of cookies and similar technologies as described in this policy. If you use the Site without changing your browser or device settings to disable cookies, we'll assume that you consent to receive all cookies provided through the Site.`}</p>
                        <p><strong>{t`Device ID and Location.`}</strong> {t`When you access or leave the Site, we receive the URL of both the site you came from and the one you go to next. We also get information about your IP address, proxy server, operating system, web browser and add-ons, device identifier and features, and/or ISP or your mobile carrier. We also receive data from your devices and networks, including location data. If you use the Site from a mobile device, that device will send us data about your device and GPS location based on your phone settings and access you have granted to the Site.`}</p>
                        <p>{t`We use this information to provide an efficient Site experience for you and to communicate with you more effectively. The information is also collected to determine the aggregate number of unique devices using the Site and/or parts of the Site, track total usage, and analyze usage data to improve Site functionality for all Members and Visitors. We may combine this information with information from third parties to provide you with a better experience and to improve the quality of our service.`}</p>
                        <p>{t`We do not share any of your personally identifiable information along with your device identification or location without your explicit permission. When required by your device operating system or internet browser, we will ask you to opt-in before we use GPS or other tools to identify your precise location. However, we may automatically collect certain details of your use of the Site, including traffic data, location data, logs, and other communication data and the resources that you access and use on or through the Site. We may collect information about your computer and mobile device and internet connection, including the mobile device’s unique device identifier, IP address, operating system, browser type, and mobile network information. If you do not want us to collect this information you should cease use of the Site.`}</p>
                        <p><strong>{t`Your Communications Directly To Us`}</strong> {t`We collect information about you when you send, receive, or engage with messages with us, including when you submit personal information or requests by emailing connect@mannahouseresource.com. We retain those communications to process your inquiries, respond to your requests, and improve our services.`}</p>
                        <p><strong>{t`Personal Information`}</strong> {t`We may tie information we do collect automatically as described above to personal information you provide to us to tailor the Site to you and make suggestions about Mannahouse Resource services and functionality as described above. Mannahouse is constantly seeking new and improved ways to offer the Site and improve online ministry. As we improve the Site, this may mean the collection of new data or new ways to use data. Because the Site is dynamic, and we continuously seek to offer new features, we may require the collection of new information. If we collect materially different personal data or materially change how we use your data, we will notify you and may also modify this Privacy Policy.`}</p>
                        <h1>{t`Third-party Information Collection`}</h1>
                        <p>{t`This Privacy Policy applies only to sites and apps that are owned and operated by Mannahouse. Please keep in mind that the Site may contain links to other websites or apps. You are responsible for reviewing the privacy statements and policies of those other websites you choose to link to or from Mannahouse Resource or the Site, so that you can understand how those websites collect, use and store your information. We are not responsible for the privacy statements, policies or content of other websites or apps, including websites you link to or from the Site. Websites containing co-branding (referencing our name and a third party’s name) contain content delivered by the third party and not us.`}</p>
                        <p>{t`Mannahouse cannot regulate other sites, content, or applications linked or provided from within the Site and our various web sites and services. Some content or applications, including partner offers, on or in Mannahouse Resource properties may be served by third-parties, including content providers, application providers, analytics companies, your mobile device manufacturer, and your mobile service provider. These other sites may place their own cookies or other files on your computer, collect data or solicit personal information from you. The information they collect may be associated with your personal information or they may collect information, including personal information, about your online activities over time and across different websites, apps, and other online services. They may use this information to provide you with interest-based (behavioral) targeted content. We do not control these third parties' tracking technologies or how they may be used. If you have any questions about targeted content, you should contact the responsible provider directly.`}</p>
                        <h1>{t`Disclosure of Your Information`}</h1>
                        <h2>{t`Disclosure on Your Behalf`}</h2>
                        <p>{t`We may disclose personal information that we collect or you provide as described in this Privacy Policy to fulfill our obligations under our Terms of Use, the purpose for which you provide it, for any other purpose you request when you provide the information, or for any other purpose for which we have your consent.`}</p>
                        <h2>{t`Internal Disclosure`}</h2>
                        <p>{t`We will share your personal data internally within Mannahouse to help combine the personal information covered across the different aspects of the Site and our other products and services to help provide services to you in a manner that is personalized and useful to you and others. For example, we can personalize potential services to recommend to you using cookies or similar technologies that track what functionality you have already opted to receive.`}</p>
                        <h2>{t`Disclosure to Our Service Providers`}</h2>
                        <p>{t`We may disclose personal information that we collect or you provide as described in this Privacy Policy to contractors, service providers and other third parties we use solely to support our mission (such as cloud hosting, maintenance, analysis, audit, payments, fraud detection, communication, and development). For example, some of the services used to send emails and notifications are built and managed by third parties, so some of your information is sent securely to those services to provide such functionality. They will have access to your information as reasonably necessary to perform these tasks on our behalf and are obligated not to disclose or use it for other purposes.`}</p>
                        <h2>{t`Legal Process`}</h2>
                        <p>{t`It is possible that we will need to disclose information about you when required by law, subpoena, or other legal process or if we have a good faith belief that disclosure is reasonably necessary to (1) investigate, prevent, or take action regarding suspected or actual illegal activities or to assist government enforcement agencies; (2) enforce our agreements with you; (3) investigate and defend ourselves against any third-party claims or allegations; (4) protect the security or integrity of the Site; or (5) exercise or protect the rights and safety of Mannahouse, our Members and/or Visitors, personnel, or others. We attempt to notify Members about legal demands for their personal data when appropriate in our judgment, unless prohibited by law or court order or when the request is an emergency. We may dispute such demands when we believe, in our discretion, that the requests are overbroad, vague, or lack proper authority, but we do not promise to challenge every demand.`}</p>
                        <h1>{t`Your Rights to Deleting, Accessing and Correcting Your Information`}</h1>
                        <h2>{t`Disclosure on Your Behalf`}</h2>
                        <p>{t`For personal data that we have about you, you have the following rights:`}</p>
                        <ul>
                            <li>{t`Deletion: You may ask us to erase or delete all or some of your personal data. Please note that doing so may limit your ability to use certain functionality of the Site. Please note that an email address is required to have a Member account.`}</li>
                            <li>{t`Correction/Modification: You may edit some of your personal data through your account or ask us to change, update, or fix your data in certain cases, including if it’s inaccurate.`}</li>
                            <li>{t`Object to, or Limit or Restrict, Use of Data: You can ask us to stop using all or some of your personal data (for example, if we have no legal right to keep using it) or to limit our use of it (for example, if your personal data is inaccurate or unlawfully held).`}</li>
                            <li>{t`Right to Access and/or Take Your Data: You can ask us for a copy of your personal data you provided to us.`}</li>
                        </ul>
                        <p>{t`To make these or any other requests with respect to your personal information, you may send us an e-mail to connect@mannahouseresource.com. You may also contact us at: Attn Global, 9200 NE Fremont St, Portland OR 97220. We ask that individuals making requests identify themselves and identify the information requested to be accessed, corrected or removed before we process any requests. We may decline to process requests if we cannot verify the requestor's identity, if we believe the request will jeopardize the privacy of others, if we believe the change would violate any law or legal requirement or cause the information to be incorrect, or for a similar legitimate purpose. In any case, where we provide information access, deletion or correction, we perform this service free of charge, except if doing so would require a disproportionate effort.`}</p>
                        <p>{t`If you choose to close your account or ask that we modify or delete some or all of your personal information, we will retain your personal data if reasonably necessary to comply with our legal obligations (including law enforcement requests), meet regulatory requirements, resolve disputes, maintain security, prevent fraud and abuse, enforce our Terms of Use or fulfill any others requests from you (for example, to opt-out of further messages or for a copy of your data).`}</p>
                        <p>{t`Mannahouse reserves the right to maintain your information, including inferences made with your information after deletion of an account. For example, while we will delete your email address if your account is deleted, we will maintain and reserve the right to use and share what aggregated statistics your activity was part of in a manner that does not identify you personally. We will also retain our aggregate count of the number to total Site applications subscribed to which would include the fact of you accessing the Site without maintaining personal information associated with that account.`}</p>
                        <p>{t`We have no control of information you have shared with others through the Site after you close your account or asked to delete information or attempted to delete your account yourself. Your information and content you have shared may continue to be displayed in the services of others (for example, search engine results) until they refresh their cache.`}</p>
                        <h2>{t`Notice to California Residents – California Privacy Rights`}</h2>
                        <p>{t`If you are a California resident and have provided us with personal information, California law requires that we provide you with a summary of your privacy rights under the California Online Privacy Protection Act (the “Act”) and the California Business and Professions Code. As required by the Act, we will provide you with the categories of personally identifiable information that we collect through the Site and the categories of third party persons or entities with whom such personally identifiable information may be shared for direct marketing purposes at your request. California law requires us to inform you, at your request, (1) the categories of personally identifiable information we collect and what third parties we share that information with; (2) the names and addresses of those third parties; and (3) examples of the products marketed by those companies. The Act further requires us to allow you to control who we can and cannot share that information with. To obtain this information, please send a request to hello@mannahouse.church and include the phrase “California Privacy Request” in the subject line. When contacting us, please indicate your name, address, email address, and what personally identifiable information you do not want us to share with third parties. Please allow thirty (30) days for a response. Also, please note that there is no charge for controlling the sharing of your personally identifiable information or requesting this notice.`}</p>
                        <h2>{t`Security and Protection`}</h2>
                        <p>{t`We implement industry-standard security safeguards designed to protect your data. These include using encryption for your data while it is being transmitted between your device or browser and our servers.`}</p>
                        <p>{t`However, given the nature of communications and information technology, and that the use of the internet has inherent risks, although we regularly monitor for possible vulnerabilities and attack, we cannot warrant or guarantee that information provided to us through the Site or stored in our systems or otherwise will be absolutely free from unauthorized intrusion by others, nor can we warrant or guarantee that such data may not be accessed, disclosed, altered, or destroyed by breach of any of our physical, technical, or managerial safeguards.`}</p>
                        <h2>{t`Processing of Data`}</h2>
                        <p>{t`We will only collect and process personal data about you where we have lawful bases. Lawful bases include consent (where you have given consent), contract (where processing is necessary for the performance of a contract with you (such as providing Site and Site functionality you request and acting in accordance with this Privacy Policy and our Terms of Use) and other legitimate interests. Such legitimate interest include protection to you, us and other Members and third parties, to comply with applicable law, to enable and administer our business, to manage corporate transactions, to generally understand and improve our business and user relationships, and to enable us and other users of the Site to connect with you to exchange information, provided that the foregoing adequately protects your rights and freedoms.`}</p>
                        <p>{t`Where we rely on your consent to process personal data, you have the right to withdraw or decline your consent at any time and where we rely on legitimate interests, you have the right to object. If you have any questions about the lawful bases upon which we collect and use your personal data, please contact us at connect@mannahouseresource.com.`}</p>
                        <h2>{t`Users From Outside the United States`}</h2>
                        <p>{t`Mannahouse Resource is offered in and from Oregon within the United States and your use of the Site and this Privacy Policy is governed by the laws of the United States and the State of Oregon. If you are using the Site from outside the United States, please be aware that your information may be transferred to, stored, and processed in the United States where our servers are located and our central database is operated. We process data both inside and outside of the United States and rely on legally-provided mechanisms to lawfully transfer data across borders. This includes contractual commitments between us and companies transferring personal data that require the protection and security of such data. The data protection and other laws of the State of Oregon, the United States, and other countries might not be as comprehensive as those in your country. By using the Site, you consent to your information being transferred to our facilities and to the facilities of those third-parties with whom we share it with as described in this Privacy Policy.`}</p>
                        <h2>{t`Changes to Our Privacy Policy`}</h2>
                        <p>{t`We may update our Privacy Policy from time to time to reflect changes in our practices. We will post any changes to our Privacy Policy on this page. If we make material changes to how we treat our users’ personal information, we will provide a notice that the Privacy Policy has been updated. The date the Privacy Policy was last modified is identified at the top of the page. You are responsible for ensuring we have an up-to-date active and deliverable email address for you, and for periodically visiting this Privacy Policy to check for any changes.`}</p>
                        <h2>{t`Children Under the Age of 16`}</h2>
                        <p>{t`We do not collect personal information from any person we actually know is under the age of 16 without the consent of the parent or legal guardian of that minor. A parent or guardian may consent to the use of the Site by a minor, which parent or guardian is solely responsible for providing supervision of the minor’s use of the Site and assumes full responsibility for the interpretation and use of any information or suggestions provided through the Site. If you believe we might have any information from or about a child under 16, please contact us at hello@mannahouse.church. If we learn and have confirmation we have collected or received personal information from a child under 16 without verification of parental consent, we will delete that information.`}</p>
                        <h2>{t`Contact Information`}</h2>
                        <p>{t`To ask questions or comment about this Privacy Policy and our privacy practices, you may contact us at: Mannahouse Church, Attn Global, 9200 NE Fremont St, Portland OR 97220; connect@mannahouseresource.com`}</p>
                    </div>
                </div>
            </div>
        </Layout>
    );
};

export default PrivacyPolicy;